Vagrant.configure("2") do |config|
	config.vm.box = "generic/alpine38"
	config.vm.provider "hyperv"
	config.vagrant.plugins = ["vagrant-winnfsd", "vagrant-vbguest"]

	config.vm.provision "shell", inline: <<-SHELL
		sudo apk add  cifs-utils
	SHELL

  	config.vm.synced_folder "./public", "/var/www/localhost/htdocs", type: "smb", 
  	create: true, group: "vagrant", owner: "vagrant",
  	mount_options: ['vers=3.0']

	config.vm.provider "hyperv" do |h|
		h.memory = 768
	end

  	config.vm.provision :shell,  :path => "test.sh"

end